### ISSUE TITLE
number of blocks requeted should not be increased above number of blocks delivered

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/turtlecoin-wallet-backend-js#74]
Some nodes (the cache) are enforcing a maximum blocks per request (25 right now). However, the ramping up/down based on whether the request succeeded does not account for this: despite the cache returning only 25 blocks successfully, the backend increases its request amount to 50, and then to 100. if 25 does happen to time out at this point, the backend will "reduce" the request to 50, which will obviously not change anything. Furthermore, it will take 3 consecutive timeouts to tangibly reduce the request at this point.

**Comment by zpalmtree** [comment]
I don't know if this is easy to implement, how do we know the amount of blocks the node is returning? Sure, it might return 25 right now, but perhaps that's for a specific range of blocks which are larger? Or because we're nearly synced so we get less blocks?

In this case we know it's 25 fixed but it's unclear if this change is going to be permanent, whether it will only apply to a range of blocks, or will be altered in some other way.
It's hard to decide what we should do as a client given incomplete information from a node.

**Comment by brandonlehmann** [comment]
> I don't know if this is easy to implement, how do we know the amount of blocks the node is returning? Sure, it might return 25 right now, but perhaps that's for a specific range of blocks which are larger? Or because we're nearly synced so we get less blocks?
> 
> In this case we know it's 25 fixed but it's unclear if this change is going to be permanent, whether it will only apply to a range of blocks, or will be altered in some other way.
> It's hard to decide what we should do as a client given incomplete information from a node.

The cache change is non-permanent. I plan to have it lifted on or before 2.2M as the load on the network is returning to “normal” and I’m deploying more resources to account for more bursts in traffic.
